GET  http://localhost:8000/blogs/ HTTP/1.1
content-type: application/json


###

DELETE  http://localhost:8000/blogs/10a39a88-3af6-4ed3-9532-989c67db01d4 HTTP/1.1
content-type: application/json



###

POST http://localhost:8000/blogs HTTP/1.1
content-type: application/json

{
    "title": "kajvckue"
}

###

PUT  http://localhost:8000/blogs/7978e88e-4b64-4b16-84d1-59dd8d10b5a9 HTTP/1.1
content-type: application/json

{
    "title": "Bloggg"
}